import type { CanvasEdge, CanvasNode } from "../../store/canvasStore";
import type { OrchestratorTask } from "./schema";

// Pure task-graph -> canvas-graph layout. Every task becomes a pair of nodes — an editable
// promptNode (matches PromptNode.tsx's existing textarea/updateNodeData pattern exactly) feeding
// a single-action actionContainerNode whose command is the same rendered CLI invocation for
// every task in the run (see build_task_command_line in src-tauri/src/agents/mod.rs). Tasks are
// laid out left-to-right in columns by dependency rank, matching promptNode's output-on-right /
// actionContainerNode's input-on-left port geometry, with parallel siblings stacked vertically.

const TASK_NODE_WIDTH = 280;
const INNER_GAP = 50;
const PAIR_WIDTH = TASK_NODE_WIDTH * 2 + INNER_GAP;
const PAIR_HEIGHT = 190;
const ROW_GAP = 50;
const COLUMN_GAP = 100;
const FRAME_SIDE_PADDING = 40;
const FRAME_TOP_PADDING = 70;
const FRAME_BOTTOM_MARGIN = 50;

export interface MaterializedGraph {
  nodes: CanvasNode[];
  edges: CanvasEdge[];
}

// Ranks each task by its longest dependency chain (0 = no deps). Depth is capped defensively —
// schema.ts's parseTaskListJson already rejects cyclic dependency graphs before this ever runs,
// so the cap is just insurance against a future caller skipping that validation.
function computeRanks(tasks: OrchestratorTask[]): Map<string, number> {
  const byId = new Map(tasks.map((t) => [t.id, t]));
  const ranks = new Map<string, number>();
  const depthCap = tasks.length + 1;

  function rankOf(id: string, depth: number): number {
    const cached = ranks.get(id);
    if (cached !== undefined) return cached;
    if (depth > depthCap) return 0;

    const task = byId.get(id);
    const dependsOn = task?.dependsOn ?? [];
    const rank = dependsOn.length === 0 ? 0 : 1 + Math.max(...dependsOn.map((dep) => rankOf(dep, depth + 1)));
    ranks.set(id, rank);
    return rank;
  }

  for (const task of tasks) rankOf(task.id, 0);
  return ranks;
}

function promptNodeId(taskId: string): string {
  return `promptNode-${taskId}`;
}

function actionNodeId(taskId: string): string {
  return `actionContainerNode-${taskId}`;
}

function makeEdge(source: string, sourceHandle: string, target: string, targetHandle: string): CanvasEdge {
  return { id: `e-${source}-${sourceHandle}-${target}-${targetHandle}`, source, sourceHandle, target, targetHandle };
}

function describeTask(task: OrchestratorTask): string {
  const scope = task.fileScopes.length > 0 ? task.fileScopes.join(", ") : "unscoped";
  const deps = task.dependsOn.length > 0 ? ` · depends on ${task.dependsOn.join(", ")}` : "";
  return `Scope: ${scope}${deps}`;
}

export function materializeTaskGraph(
  tasks: OrchestratorTask[],
  frameLabel: string,
  frameId: string,
  taskCommand: string
): MaterializedGraph {
  const ranks = computeRanks(tasks);
  const maxRank = Math.max(0, ...Array.from(ranks.values()));

  const columns: OrchestratorTask[][] = Array.from({ length: maxRank + 1 }, () => []);
  for (const task of tasks) columns[ranks.get(task.id) ?? 0].push(task);

  const maxRows = Math.max(...columns.map((c) => c.length));
  const frameWidth = FRAME_SIDE_PADDING * 2 + columns.length * PAIR_WIDTH + Math.max(0, columns.length - 1) * COLUMN_GAP;
  const frameHeight =
    FRAME_TOP_PADDING + maxRows * PAIR_HEIGHT + Math.max(0, maxRows - 1) * ROW_GAP + FRAME_BOTTOM_MARGIN;

  const nodes: CanvasNode[] = [
    {
      id: frameId,
      type: "actionFrameNode",
      x: 0,
      y: 0,
      width: frameWidth,
      height: frameHeight,
      data: { label: frameLabel, description: "Generated by the orchestrator" },
    },
  ];
  const edges: CanvasEdge[] = [];

  columns.forEach((column, columnIndex) => {
    const colX = FRAME_SIDE_PADDING + columnIndex * (PAIR_WIDTH + COLUMN_GAP);
    column.forEach((task, rowIndex) => {
      const rowY = FRAME_TOP_PADDING + rowIndex * (PAIR_HEIGHT + ROW_GAP);
      const promptId = promptNodeId(task.id);
      const actionId = actionNodeId(task.id);

      nodes.push({
        id: promptId,
        type: "promptNode",
        x: colX,
        y: rowY,
        width: TASK_NODE_WIDTH,
        height: PAIR_HEIGHT,
        parentId: frameId,
        data: { label: task.title, prompt: task.prompt },
      });
      nodes.push({
        id: actionId,
        type: "actionContainerNode",
        x: colX + TASK_NODE_WIDTH + INNER_GAP,
        y: rowY,
        width: TASK_NODE_WIDTH,
        height: PAIR_HEIGHT,
        parentId: frameId,
        data: {
          label: `${task.title} — Execute`,
          description: describeTask(task),
          actions: [taskCommand],
        },
      });

      edges.push(makeEdge(promptId, "output", actionId, "input"));
      for (const dep of task.dependsOn) {
        edges.push(makeEdge(actionNodeId(dep), "output", promptId, "trigger"));
      }
    });
  });

  return { nodes, edges };
}
