import { useState, FormEvent } from "react";
import { Sparkles, ArrowRight, Loader2 } from "lucide-react";
import { useCanvasStore, CanvasNode } from "../../store/canvasStore";
import { parseOrchestratorGoal } from "../../lib/orchestratorParser";

const CHILD_WIDTH = 320;
const CODER_HEIGHT = 190;
const ACTION_HEIGHT = 240;
const CHILD_GAP = 70;
const FRAME_SIDE_PADDING = 40;
const FRAME_TOP_PADDING = 70;
const FRAME_BOTTOM_MARGIN = 50;

// Finds an empty spot to the right of every existing node so successive orchestrator runs
// never stack their generated plans on top of one another.
function findDropPosition(nodes: CanvasNode[]): { x: number; y: number } {
  if (nodes.length === 0) return { x: 120, y: 160 };
  const maxX = Math.max(...nodes.map((n) => n.x + n.width));
  return { x: maxX + 140, y: 140 };
}

// Parses the goal, drops the resulting Coder/Reviewer/Test Runner nodes nested inside a new
// Figma-style Action Frame, and wires their cables in sequence: pure client-side layout, no
// network call involved.
function runOrchestrator(goal: string) {
  const store = useCanvasStore.getState();
  const plan = parseOrchestratorGoal(goal);
  const { x: startX, y: startY } = findDropPosition(store.nodes);

  if (plan.kind === "ephemeral") {
    const id = store.addNode("ephemeralActionNode", startX, startY, {
      data: { label: plan.label, command: plan.command, status: "idle", ephemeral: true },
    });
    store.setSelectedNodeIds([id]);
    return;
  }

  const maxChildHeight = Math.max(CODER_HEIGHT, ACTION_HEIGHT);
  const frameWidth =
    FRAME_SIDE_PADDING * 2 + plan.nodes.length * CHILD_WIDTH + (plan.nodes.length - 1) * CHILD_GAP;
  const frameHeight = FRAME_TOP_PADDING + maxChildHeight + FRAME_BOTTOM_MARGIN;

  const frameId = store.addNode("actionFrameNode", startX, startY, {
    width: frameWidth,
    height: frameHeight,
    data: { label: plan.frameLabel, description: "Generated by Canvas Architect" },
  });

  const createdIds = plan.nodes.map((planNode, i) => {
    const isCoder = planNode.role === "coder";
    const type: CanvasNode["type"] = isCoder ? "promptNode" : "actionContainerNode";
    const height = isCoder ? CODER_HEIGHT : ACTION_HEIGHT;
    const nodeX = startX + FRAME_SIDE_PADDING + i * (CHILD_WIDTH + CHILD_GAP);
    const nodeY = startY + FRAME_TOP_PADDING + (maxChildHeight - height) / 2;

    return store.addNode(type, nodeX, nodeY, {
      parentId: frameId,
      width: CHILD_WIDTH,
      height,
      data: {
        label: planNode.label,
        role: planNode.role,
        description: planNode.description,
        prompt: planNode.prompt,
        actions: planNode.actions,
      },
    });
  });

  for (let i = 0; i < createdIds.length - 1; i++) {
    store.addEdge(createdIds[i], "output", createdIds[i + 1], "input");
  }

  store.setSelectedNodeIds([frameId, ...createdIds]);

  const vp = store.viewport;
  store.setViewport({ x: 220 - startX * vp.zoom, y: 180 - startY * vp.zoom });
}

export default function OrchestratorBar() {
  const [value, setValue] = useState("");
  const [isRunning, setIsRunning] = useState(false);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    const goal = value.trim();
    if (!goal || isRunning) return;

    setIsRunning(true);
    try {
      runOrchestrator(goal);
      setValue("");
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <div className="h-12 shrink-0 border-b border-slate-800/80 bg-slate-950/70 backdrop-blur-md px-4 flex items-center gap-3 z-10 select-none">
      <div className="flex items-center gap-1.5 text-indigo-400 shrink-0">
        <Sparkles size={14} />
        <span className="text-[10px] font-semibold uppercase tracking-wider hidden md:inline">
          Canvas Architect
        </span>
      </div>
      <form onSubmit={handleSubmit} className="flex-1 flex items-center gap-2 min-w-0">
        <input
          type="text"
          value={value}
          onChange={(e) => setValue(e.target.value)}
          placeholder='Describe what to build… e.g. "Build an auth handler with unit tests and a security reviewer"'
          className="flex-1 min-w-0 bg-slate-900 border border-slate-800 focus:border-indigo-500/60 rounded-lg px-3 py-1.5 text-xs text-slate-200 placeholder-slate-600 focus:outline-none font-mono transition-colors"
        />
        <button
          type="submit"
          disabled={!value.trim() || isRunning}
          className="flex items-center gap-1.5 bg-indigo-500 hover:bg-indigo-400 active:bg-indigo-600 disabled:opacity-40 disabled:cursor-not-allowed text-slate-950 font-semibold px-3 py-1.5 rounded-lg text-[11px] tracking-wide transition-all cursor-pointer shrink-0"
        >
          {isRunning ? <Loader2 size={12} className="animate-spin" /> : <ArrowRight size={12} />}
          Generate
        </button>
      </form>
    </div>
  );
}
